require(ursa)
p1 <- spatial_read("Polynya_2.gpkg")
p2 <- spatial_read("Polynya_2.shz")
spatial_crs(p2)
sum(spatial_area(p1))
sum(spatial_area(p2))
identical(spatial_crs(p1),spatial_crs(p2))
identical(spatial_geometry(p1),spatial_geometry(p2))
identical(spatial_coordinates(p1),spatial_coordinates(p2))
identical(spatial_data(p1["Desc"]),spatial_data(p2["Desc"]))
#spatial_data(p1["Desc"])
#spatial_data(p2["Desc"])
p <- ursa_read("Karskoe_modified.tif")
spatial_crs(p)
display_rgb(p,graticule.lon=seq(0,350,by=10),graticule.lat=seq(0,80,by=10),col="black")
glance(p2["Desc"],graticule.col="black",costline.col="black",lwd=1,resetProj=TRUE)
