require(ursa)
p <- ursa_read("Karskoe_modified.tif")
spatial_crs(p)
display_rgb(p,graticule.lon=seq(0,350,by=10),graticule.lat=seq(0,80,by=10),col="black")
pol <- spatial_read("Polynya.shz")
spatial_crs(pol)
pol <- ursa:::spatialize(pol,style="laea",border=0)
spatial_crs(pol)
session_grid(pol)
compose_open()
panel_new("white")
ct <- panel_plot(pol["Desc"],lwd=1,border="black")
panel_decor(graticule.lon=seq(0,350,by=10),graticule.lat=seq(0,80,by=10),col="black")
compose_legend(ct)
compose_close()
