require(ursa)
options(ursaProj4Legacy=TRUE)
list1 <- lapply(spatial_dir(),spatial_read)
str(lapply(list1,spatial_fields))
p <- lapply(list1,\(x) x[,c("id","NAME","id_2")]) |> spatial_bind()
spatial_crs(p)
p <- ursa:::spatialize(p,resetProj=TRUE)
spatial_crs(p)
p$id_3 <- seq(spatial_count(p))
spatial_data(p)
# glance(p,blank="white",coast.fill="#00000010")
p$Area <- spatial_area(p)*1e-6
spatial_data(p)
pc <- spatial_centroid(p)
pc$Area <- sprintf("%.0f",pc$Area)
compose_open()
panel_new("layout")
panel_plot(p["id_3"],col=palettize(p$id_3,pal.bright=191,pal.rotate="circle"))
panel_annotation(pc["Area"])
panel_decor(coast.fill="#00000010")
compose_close()
