```{r setup, echo=FALSE, include=FALSE}
filetype <- knitr::opts_knit$get("rmarkdown.pandoc.to")[1] ## "revealjs" "html"
sound <- T
isRevealjs <- filetype %in% "revealjs"
# rendertyoe <- rmarkdown::default_output_format(knitr::current_input())$name
rendertype <- rmarkdown::all_output_formats(knitr::current_input())[1]
#knitr::opts_chunk$set(collapse=FALSE,prompt=FALSE,comment=""
#                     ,cache=TRUE
#                     ,echo=FALSE,fig.align="center"
#                     )
'h1' <- function(lab,ref="",center=TRUE,invert=NA,background="",subtitle=TRUE
                ,scale=NA,opt="",radio=F,eval=TRUE) {
   if (missing(lab)) {
      if (!isRevealjs)
         return("")
      lab <- ""
      if (!nchar(background))
         background <- "picsum"
   }
   if (!eval)
      return("")
   mycol <- paste0(ursa::cubehelix(1,dark=61,light=61,hue=1.5),"B0")
  # subtitle <- FALSE
   if (is.na(invert))
      invert <- center
   if (length(grep("(random|picsum)",background,ignore.case=TRUE)))
      background <- file.path("https://picsum.photos"
                            # ,"seed",paste(sample(letters,6,replace=TRUE),collapse="")
                             ,"1052/744"
                             ,paste0("?random=",sample(10:99,1))
                             )
                            # ,"?blur=1"
                            # ,paste0("?blur=5&random=",paste(sample(letters,3,replace=TRUE),collapse="")))
   else if ((invert)&&(!nchar(background)))
      background <- mycol
   if (!nchar(ref)) {
      if (F) {
         if (length(grep("[А-Яа-я]",lab))>=0) {
            ref <- basename(tempfile(pattern="",fileext=""))
            ref <- paste0("ref",substr(ref,nchar(ref)-3L,nchar(ref)))
         }
      }
      else {
         refN <- getOption("ongoingRef")
         if (is.null(refN))
            refN <- 1L
         ref <- paste0("r",digest::digest(paste0(lab,refN),"crc32"))
         options(ongoingRef=refN+1)
      }
   }
   res <- paste0("# ",lab," {",ifelse(center,".center "," "),"#",ref)
   if (nchar(background)) {
     # background <- normalizePath(background,winslash="/")
     # if (length(grep("^[a-z]\\:",background,ignore.case=TRUE)))
     #    background <- paste0("file:///",background)
      if (length(grep("(^(http|file).+(\\.html|\\.php|/)$)",background))) {
         res <- paste0(res," data-background-iframe=",background)
         sound <- F
      }
      else if (!length(grep("(^(http|file)|\\.(jpg|png|gif)$)",background)))
         res <- paste0(res," data-background-color=",background)
      else {
         res <- paste0(res," data-background-image=",background)
         res <- paste0(res," data-background-color=",ifelse(invert,mycol,"#F0F1EB5F"))
      }
     # res <- paste0(res," style=\"background:transparent;\"")
   }
   if (sound) {
      if (radio) {
        # res <- paste0(res," data-background-video=http://radio.4duk.ru/4duk64.mp3")
         res <- paste0(res," data-background-video=http://51.255.235.165:5528/stream")
      }
      else
         res <- paste0(res
                      ," data-background-video=https://nplatonov.github.io/transition-dong.mp3"
                     # ," data-background-opacity=0"
                      )
   }
   if (subtitle)
      res <- paste0(res," class=\"h2inherit\"")
   if ((filetype %in% c("revealjs"))&&(is.numeric(scale)))
      res <- paste0(res," style=\"font-size: ",scale,"%;\"")
   if (nchar(opt))
      res <- paste0(res," ",opt)
   res <- paste0(res,"}")
   ##~ res2 <- paste0("<section id=",dQuote(ref)
                ##~ ," class=",dQuote("title-slide slide level1")
                ##~ ," data-background=",dQuote(background),">"
                ##~ ,"<h1>",lab,"</h1></section>")
   if ((F)&&(filetype %in% "revealjs")&&(subtitle)) {
     # res <- paste0(res,"\n\n###### ",lab," {.slideheader}\n\n")
      res <- paste0("\n\n###### ",lab," {.slideheader}\n\n",res)
      ##~ res2 <- paste0(res2,"<h6 class=",dQuote("slideheader"),">",lab,"</h6>")
   }
   ##~ res2 <- paste0(res2,"</section>")
   ##~ res <- res2
   res
}
#'picsum' <- function(lab) h1(lab=lab,opt=".picsum")
'picsum' <- function() h1(opt=".picsum")
'h2' <- function(lab,entry=c("default","first","next","last"),ref=""
                ,center=F,background="",scale=NA,opt="",force=FALSE,eval=TRUE) {
   if (!eval)
      return("")
   mode <- match.arg(entry)
   if (missing(lab)) {
      lab <- getOption("ongoingH2label")
      if (mode %in% c("default"))
         mode <- "next"
      if (is.na(scale)) {
         scale <- getOption("ongoingH2scale")
         if ((is.null(scale))||((!is.numeric(scale))&&(!is.na(scale))))
            scale <- NA
      }
      if (!nchar(ref))
         ref <- getOption("ongoingH2ref")
      if (is.null(ref))
         ref <- ""
      else {
         patt <- "(.*\\D)(\\d+)$"
         n <- gsub(patt,"\\2",ref)
         if (n==ref)
            n <- 2L
         else
            n <- as.integer(n)+1L
         ref <- paste0(gsub(patt,"\\1",ref),n)
      }
   }
   else {
      options(ongoingH2label=lab,ongoingH2scale=scale)
     # if (mode %in% c("default"))
     #    mode <- "first"
   }
   if ((filetype %in% c("html"))&&(!force)&&(mode %in% c("next","last")))
      return("")
   external <- c("zoom","slide","concave","fade","ENTRY")[5]
   internal <- c("fade","ENTRY")[2]
   if (F) {
      tr <- c("none","fade","slide","convex","concave","zoom")
     # internal <- sample(tr,1)
      external <- sample(tr[3:6],1)
   }
   transition <- switch(mode
                       ,'first'=paste0(external,"-in"," ",internal,"-out")
                       ,'next'=paste0(internal,"-in"," ",internal,"-out")
                       ,'last'=paste0(internal,"-in"," ",external,"-out")
                       ,paste0(external,"-in"," ",external,"-out"))
   ##~ res <- paste0("## ",lab," {data-transition=",dQuote(transition)," ",opt
               ##~ # ,ifelse(nchar(lab),"",".dontprint")
                ##~ ,"}")
   if (!nchar(ref)) {
      if (F) {
         if (length(grep("[А-Яа-я]",lab))>=0) {
            ref <- basename(tempfile(pattern="",fileext=""))
            ref <- paste0("ref",substr(ref,nchar(ref)-3L,nchar(ref)))
         }
      }
      else {
         refN <- getOption("ongoingRef")
         if (is.null(refN))
            refN <- 1L
         ref <- paste0("r",digest::digest(paste0(lab,refN),"crc32"))
         options(ongoingRef=refN+1)
      }
   }
   options(ongoingH2ref=ref)
   res <- paste0("## ",lab," {",ifelse(center,".center","")," #",ref)
   res <- paste0(res," data-transition=",dQuote(transition))
   if (nchar(background)) {
     # if (!length(grep("^http",background)))
      res <- paste0(res," data-background=",background)
   }
   if (sound)
      res <- paste0(res
                   ," data-background-video=https://nplatonov.github.io/transition-ding.mp3"
                  # ," data-background-opacity=0"
                   )
  # if (mode %in% c("default","first"))
  #    res <- paste0(res," class=\"putheader\"")
   if ((filetype %in% c("revealjs"))&&(is.numeric(scale)))
      res <- paste0(res," style=\"font-size: ",scale,"%;\"")
   if (nchar(opt))
      res <- paste0(res," ",opt)
   res <- paste0(res,"}")
   res
}
'h3' <- function(lab,entry=c("default","first","next","last"),ref=""
                ,opt="",force=FALSE) {
   mode <- match.arg(entry)
   if ((filetype %in% c("html"))&&(!force)&&(mode %in% c("next","last")))
      return("")
   if (!nchar(ref)) {
      if (F) {
         if (length(grep("[А-Яа-я]",lab))>=0) {
            ref <- basename(tempfile(pattern="",fileext=""))
            ref <- paste0("ref",substr(ref,nchar(ref)-3L,nchar(ref)))
         }
      }
      else {
         refN <- getOption("ongoingRef")
         if (is.null(refN))
            refN <- 1L
         ref <- paste0("r",digest::digest(paste0(lab,refN),"crc32"))
         options(ongoingRef=refN+1)
      }
   }
   res <- paste0("### ",lab," {#",ref)
   if (nchar(opt))
      res <- paste0(res," ",opt)
   res <- paste0(res,"}")
   res
}
'references' <- function(label="",scale=NA,inline=T) {
   res <- character()
   if (F & !isRevealjs)
      return(res)
   if (!inline) {
      ref <- basename(tempfile(pattern="",fileext=""))
      ref <- paste0("ref",substr(ref,nchar(ref)-3L,nchar(ref)))
      res <- paste0(res,"## {#",ref,"}\n")
   }
   res <- paste0(res,":::{class=\"references\" id=\"refs\"")
   if (!is.na(scale))
      res <- paste0(res," style=\"font-size:",scale,"% !important;\"")
   res <- paste0(res,"}\n:::")
   res
}
```

```{r, include=FALSE, eval=FALSE}
print(c(filetype=filetype,rendertype=rendertype))
```
