require(ursa)
options(ursaProj4Legacy=TRUE)
a1 <- ursa_read("карта1.tif")
a2 <- ursa_read("карта2.tif")
ursa_crs(a1)
ursa_crs(a2)
a3 <- a1+as.integer(round(ursa:::.gdalwarp(a2,grid=a1,resample="bilinear")))
a1 <- ursa_crop(a1,a1[4]>0)
display(a1,graticule.lon=seq(0,350,by=10),graticule.lat=seq(0,80,by=10),col="black")
a2 <- ursa_crop(a2,a2[4]>0)
display(a2,graticule.lon=seq(0,350,by=10),graticule.lat=seq(0,80,by=10),col="black")
a3 <- ursa_crop(a3,a3[4]>0)
display(a3,graticule.lon=seq(0,350,by=10),graticule.lat=seq(0,80,by=10),col="black")
p <- spatial_read("площадь.shz")
spatial_crs(p)
spatial_data(p)
p <- ursa:::spatialize(p,resetProj=TRUE)
pc <- spatial_centroid(p)
pc$area <- sprintf("%.0f",pc$area)
session_grid(p)
compose_open(height=2000,pointsize=12)
panel_new("layout")
panel_raster(a3)
panel_plot(p["name"],col=palettize(p$name,pal.bright=191,pal.rotate="circle"),alpha=0.6)
panel_decor(coast.fill="#00000010"
           ,graticule.lon=seq(0,350,by=10),graticule.lat=seq(0,80,by=10),col="black")
panel_annotation(pc["area"],buffer=1.4)
compose_close()
