require(ursa)
options(ursaProj4Legacy=TRUE)
a1 <- ursa_read("atlas_karsk.tif")
a2 <- ursa_read("atlas_franz2k.tif")
ursa_crs(a1)
ursa_crs(a2)
a1 <- a1[local_sum(a1)>0]
a2 <- a2[local_sum(a2)>0]
# display(a1,graticule.lon=seq(0,350,by=10),graticule.lat=seq(0,80,by=10),col="black")
# display(a2,graticule.lon=seq(0,350,by=10),graticule.lat=seq(0,80,by=10),col="black")
p <- spatial_read("Liman_Sarea.shz")
spatial_crs(p)
spatial_data(p)
p <- ursa:::spatialize(p,resetProj=TRUE)
pc <- spatial_centroid(p)
pc$area <- sprintf("%.0f",pc$'S area')
session_grid(p)
compose_open(height=2000,pointsize=12)
panel_new("layout")
panel_raster(a1)
panel_plot(p["Name"],col=palettize(p[['Name']],pal.bright=191,pal.rotate="circle"),alpha=0.6)
panel_decor(coast.fill="#00000010"
           ,graticule.lon=seq(0,350,by=10),graticule.lat=seq(0,80,by=10),col="black")
panel_annotation(pc["area"],buffer=1.4)
compose_close()
