plutil::ursula(3)
a <- sf::st_crs("карта.prj")
a <- spatial_crs(a)
gcp <- read.csv("карта.jpg.points",skip=1)
gcp$sourceY <- -gcp$sourceY
gcp$no <- seq_len(nrow(gcp))
b1 <- spatialize(gcp,coords=c("mapX","mapY"),crs=a)
if (T)
   b1 <- spatialize(b1,resetGrid=TRUE,lon0=80)
g1 <- spatial_grid(b1)
#spatial_data(b1) <- data.frame(no=seq(spatial_count(b1)))
#glance(b1)
session_grid(NULL)
#b2 <- spatialize(gcp,coords=c("sourceX","sourceY"),crs=character())
#spatial_data(b2) <- data.frame(no=seq(spatial_count(b2)))
p <- ursa_read("карта.jpg")
#spatial_crs(b2) <- spatial_crs(p)
compose_open(2,scale=1,legend=NULL,fileout="карта.png",bpp=8)
panel_new()
panel_raster(p)
panel_points(x=gcp$sourceX,y=gcp$sourceY,pch=19,cex=3,col="white")
panel_text(x=gcp$sourceX,y=gcp$sourceY,labels=gcp$no)
panel_decor()
panel_new(grid=regrid(g1,expand=1.2),"white")
xy <- spatial_coordinates(b1)
panel_points(x=xy[,1],y=xy[,2],pch=19,cex=3,col="yellow")
panel_text(x=xy[,1],y=xy[,2],labels=gcp$no)
# panel_plot(b1["no"])
panel_decor()
compose_close()
