plutil::ursula()
options(ursaProj4Legacy=TRUE)
session_grid(NULL)
a <- ursa_read("poly_modified2.tif")
ursa_crs(a)
session_grid(NULL)
p1 <- spatial_read("SNZP+UNZP+AP.gpkg")
p2 <- spatial_read("ZSZP+CKP+OEP+AP-2.gpkg")
p <- spatial_bind(p1,p2)
spatial_crs(p)
p$'$area_km2' <- as.numeric(p[["$area"]])*1e-6
p$check_ll <- spatial_area(p)*1e-6
p <- ursa:::spatialize(p,style="laea")
spatial_crs(p)
p$check_laea <- spatial_area(p)*1e-6
spatial_data(p)
p$name <- as.character(seq(spatial_count(p)))
pc <- spatial_centroid(p)
pc$area <- sprintf("%.0f",as.numeric(pc$'$area')*1e-6)
session_grid(p,expand=1.1)
compose_open(height=2000,pointsize=12)
panel_new("layout")
panel_raster(a)
panel_plot(p["name"],col=palettize(p$name,pal.bright=191,pal.rotate="circle"),alpha=0.6)
panel_decor(coast.fill="#00000010"
           ,graticule.lon=seq(0,350,by=10),graticule.lat=seq(0,80,by=10),col="black")
panel_annotation(pc["area"],buffer=1.4)
compose_close()
